### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by LOQUILLO** [jbrooksuk/SublimeFlatColors#1]
Hi @jbrooksuk, I type this in my CSS code:
color: asbesto;

But don't change to hex code, or where I am mistaked.
ST3 Buld 3083 (Estable)
Windows 7 x64

**Comment by math2001** [comment]
Hello!
fixed in my PR https://github.com/jbrooksuk/SublimeFlatColors/pull/2. Just need to wait until @jbrooksuk accepts it...

Mathieu
